cask_args appdir: '/Applications'

brew 'git'

tap 'homebrew/services'
tap 'homebrew/bundle'

brew 'argon/mas/mas'
brew 'postgresql'
brew 'phantomjs'
brew 'gist'
brew 'openssh'
brew 'qt@5.5'
brew 'python'
brew 'wget'
brew 'openssl'
brew 'pkg-config'
brew 'node'
brew 'librsvg'
brew 'imagemagick', args: ['with-librsvg']
brew 'apm-bash-completion'
brew 'zsh'
brew 'zsh-completions'

cask 'java'
cask 'alfred'
cask 'atom'
cask 'flowdock' 
cask 'firefox'		
cask 'google-chrome'		
cask 'sourcetree'		
cask 'citrix-receiver'		
cask 'adobe-creative-cloud'		
cask 'android-platform-tools'		
cask 'android-sdk'		
cask 'android-studio'
