#!/bin/bash

cd ~/ || exit

which -s brew
if [[ $? == 0 ]] ; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
fi

#if [ -f "$HOME/Brewfile" ]; then
#  file="$HOME/Brewfile"
#  while read -r app; do
#    [[ "$app" =~ ^'cask_args'.*$ || "$app" =~ ^'tap'.*$ || "$app" =~ ^'brew'.*$ ]] && continue
#  
#    sudo rm -rf "$app"
#
#    echo "$app"
#  done < "$file"
#fi

sudo rm -rf /usr/local .* Brewfile laptop.log clean mac npm-packages Downloads/onboarding-installs bin_compciv/ SizeUp.sizeuplicense

chsh -s /bin/bash
