#!/bin/sh

if [ ! -d "$HOME/.ssh" ]; then
  mkdir ~/.ssh
  cd ~/.ssh || exit

  # shellcheck disable=SC2039
  echo -n "What is your BB&T email?"
  read -r email

  if [ ! -f "$HOME/.ssh/$response" ]; then
    ssh-keygen -t rsa -C "$response" -P "" -f "$response"

    pbcopy < "$HOME/.ssh/$response"
    pubkey=$(echo "$HOME/.ssh/$response" | pbcopy)
    export pubkey
  fi
  
  echo -n "What is the IP of the Git server?"
  read -n ip

  if [ ! -f "$HOME/.ssh/config" ]; then
    cat > ~/.ssh/config <<ENDOFCONTENT
      Host gitdesign
      HostName 192.168.1.200
      IdentityFile ~/.ssh/$email.pub
    ENDOFCONTENT
  fi

  cd ~/ || exit
fi

