#!/bin/sh

for dir in ~
do
  (
  cd "$dir" || exit
  curl --remote-name https://raw.githubusercontent.com/ethikz/onboarding-installs/master/mac
  curl --remote-name https://raw.githubusercontent.com/ethikz/onboarding-installs/master/Brewfile
  curl --remote-name https://raw.githubusercontent.com/ethikz/onboarding-installs/master/.laptop.local
  /usr/bin/env bash mac 2>&1 | tee ~/laptop.log
    
  cd ~ || exit
  )
done

