#!/bin/bash

read -r -p 'Please enter your Flowdock Login (Should be the same as your BB&T Email): ' USER

read -r -s -p 'Please enter your Flowdock Password: ' PASS

PUB=$(cat "$HOME/.ssh/${USER}.pub")
PUBKEY=$(echo ${PUB})
USERID=$(curl -k -L -u ${USER}:${PASS} "https://api.flowdock.com/users" | jq -r '.[] | select(.email == "'"${USER}"'") | .id')
GITADMIN=$(curl -k -L -u ${USER}:${PASS} "https://api.flowdock.com/users" | jq -r '.[] | select(.email == "jchristensen@bbandt.com") | .id')
SENDMSG=$(curl -k -L -i -u ${USER}:${PASS} "https://api.flowdock.com/private/${GITADMIN}/messages" -H "Content-Type: application/json" -d '{ "event": "message", "content": "'"${PUBKEY}"'" }')

echo 'Send message '"${SENDMSG}"
